/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 03:48:12 GMT 2026
 */

package edu.colostate.cs415.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.colostate.cs415.model.Company;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;
import java.util.LinkedHashSet;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Company_ESTest extends Company_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Company company0 = new Company("gHF:yiK}dPdH(c");
      company0.createQualification("gHF:yiK}dPdH(c");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createWorker("FINISHED", set0, 0.0);
      Set<Worker> set1 = company0.getUnassignedWorkers();
      assertEquals(1, set1.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      Set<Project> set1 = company0.getProjects();
      assertTrue(set1.contains(project0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      Set<Worker> set1 = company0.getEmployedWorkers();
      assertEquals(1, set1.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Company company0 = new Company("gHF:yiK}dPdH(c");
      company0.createQualification("gHF:yiK}dPdH(c");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createWorker("FINISHED", set0, 0.0);
      Set<Worker> set1 = company0.getAvailableWorkers();
      assertEquals(1, set1.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("gHF:yiK}dPdH(c", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
      
      Set<Worker> set1 = company0.getAssignedWorkers();
      assertTrue(set1.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Project> set0 = company0.getProjects();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Worker> set0 = company0.getAvailableWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Company company0 = new Company("gHF:ytK}HPdH(c");
      company0.createQualification("gHF:ytK}HPdH(c");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("gHF:ytK}HPdH(c", set0, projectSize0);
      Worker worker0 = company0.createWorker("gHF:ytK}HPdH(c", set0, 0.0);
      worker0.addProject(project0);
      company0.unassignAll(worker0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker0, project0);
      company0.unassignAll(worker0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Company company0 = new Company("gHF:yiK}dPdH(c");
      company0.createQualification("gHF:yiK}dPdH(c");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("gHF:yiK}dPdH(c", set0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassignAll(worker0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Company company0 = new Company("sY`-~Y[VHsh");
      // Undeclared exception!
      try { 
        company0.unassignAll((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker0, project0);
      company0.unassign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
      assertEquals(ProjectStatus.PLANNED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@", set0, 0.0);
      company0.unassign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Company company0 = new Company("gHF:ytK}HPdH(c");
      company0.createQualification("gHF:ytK}HPdH(c");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("gHF:ytK}HPdH(c", set0, projectSize0);
      Worker worker0 = company0.createWorker("gHF:ytK}HPdH(c", set0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Company company0 = new Company("Bh}ipp");
      company0.createQualification("Bh}ipp");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("Bh}ipp", set0, projectSize0);
      Worker worker0 = new Worker("Bh}ipp", set0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Company company0 = new Company("Bh}ipp");
      company0.createQualification("Bh}ipp");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = new Worker("tE<0I[ Y''^<G#9!", set0, 0.0);
      // Undeclared exception!
      try { 
        company0.unassign(worker0, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("d:D$HS3@", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.unassign((Worker) null, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@", set0, 0.0);
      project0.addWorker(worker0);
      Worker worker1 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker1, project0);
      assertEquals(0.0, worker1.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.finish(project0);
      company0.assign(worker0, project0);
      assertEquals(ProjectStatus.FINISHED, project0.getStatus());
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      worker0.addProject(project0);
      company0.assign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstAk+kgX{w", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker0, project0);
      company0.assign(worker0, project0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Company company0 = new Company("]");
      company0.createQualification("]");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("]", set0, 0.0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("]", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.assign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project not in company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Company company0 = new Company("Z0X");
      Qualification qualification0 = new Qualification("PLANNED");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("Company name", linkedHashSet0, 0.0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = company0.createProject("Company name", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        company0.assign(worker0, project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker not in company
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Company company0 = new Company("Yo`[H%~k S /K");
      company0.createQualification("Yo`[H%~k S /K");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("edu.colostate.cs415.model.ProjectStatus", set0, 1452.0);
      // Undeclared exception!
      try { 
        company0.assign(worker0, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project is null
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Company company0 = new Company("Yo`[H%~k S /K");
      // Undeclared exception!
      try { 
        company0.assign((Worker) null, (Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker is null
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker0, project0);
      company0.start(project0);
      company0.finish(project0);
      assertEquals(ProjectStatus.FINISHED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Company company0 = new Company("gHF:yiK}dPdH(c");
      company0.createQualification("gHF:yiK}dPdH(c");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("gHF:yiK}dPdH(c", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.finish(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      company0.finish(project0);
      assertEquals(ProjectStatus.PLANNED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Company company0 = new Company("f=N");
      // Undeclared exception!
      try { 
        company0.finish((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("d:D$HS3@", set0, projectSize0);
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      company0.assign(worker0, project0);
      company0.start(project0);
      company0.unassign(worker0, project0);
      company0.start(project0);
      assertEquals(ProjectStatus.SUSPENDED, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.ACTIVE;
      project0.setStatus(projectStatus0);
      company0.start(project0);
      assertEquals(ProjectStatus.ACTIVE, project0.getStatus());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project("X>rbJ%F", set0, projectSize0);
      // Undeclared exception!
      try { 
        company0.start(project0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Company company0 = new Company("B{p1ps");
      // Undeclared exception!
      try { 
        company0.start((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      // Undeclared exception!
      try { 
        company0.createProject("d:D$HS3@", set0, (ProjectSize) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Company company0 = new Company("4=Q");
      ProjectSize projectSize0 = ProjectSize.SMALL;
      // Undeclared exception!
      try { 
        company0.createProject("UM<:BbzRGep\"VDqg _L%", (Set<Qualification>) null, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      // Undeclared exception!
      try { 
        company0.createProject("", linkedHashSet0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      // Undeclared exception!
      try { 
        company0.createProject("G@6!>zstA'+kgX{w", set0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Qualification> set0 = company0.getQualifications();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      // Undeclared exception!
      try { 
        company0.createProject((String) null, set0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Company company0 = new Company("Z0X");
      company0.createQualification("Company name");
      Qualification qualification0 = company0.createQualification("Company name");
      assertNull(qualification0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Company company0 = new Company("Project is null");
      // Undeclared exception!
      try { 
        company0.createQualification("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Company company0 = new Company("<QB,Tv}LS<g");
      // Undeclared exception!
      try { 
        company0.createQualification((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Company company0 = new Company("Z0X");
      Qualification qualification0 = new Qualification("PLANNED");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = company0.createWorker("PLANNED", linkedHashSet0, 0.0);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Company company0 = new Company("gHF:yiK}dPdH(c");
      company0.createQualification("gHF:yiK}dPdH(c");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("FINISHED", set0, 0.0);
      assertNotNull(worker0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
      
      company0.createWorker("FINISHED", set0, 0.0);
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      company0.createQualification("d:D$HS3@:0:0");
      Set<Qualification> set0 = company0.getQualifications();
      company0.createWorker("d:D$HS3@", set0, (-1469.5));
      assertEquals(1, set0.size());
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Company company0 = new Company("4=Q");
      Worker worker0 = company0.createWorker("UM<:BbzRGep\"VDqg _L%", (Set<Qualification>) null, (-1420.0736));
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Company company0 = new Company("sY`-~Y[VHsh");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = company0.createWorker("", linkedHashSet0, 0.0);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Company company0 = new Company("r8z$-g");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker((String) null, set0, (-192.525275153746));
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Company company0 = new Company("-MDy");
      Company company1 = new Company("-MDy");
      boolean boolean0 = company0.equals(company1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      boolean boolean0 = company0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      boolean boolean0 = company0.equals(company0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      boolean boolean0 = company0.equals("d:D$HS3@");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Company name
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Company company0 = null;
      try {
        company0 = new Company((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Company name
         //
         verifyException("edu.colostate.cs415.model.Company", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Worker> set0 = company0.getUnavailableWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Company company0 = new Company("Bh}ipp");
      company0.hashCode();
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Worker> set0 = company0.getAssignedWorkers();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Worker> set0 = company0.getUnassignedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      String string0 = company0.toString();
      assertEquals("d:D$HS3@:0:0", string0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Qualification> set0 = company0.getQualifications();
      Worker worker0 = company0.createWorker("d:D$HS3@:0:0", set0, 0.0);
      assertNull(worker0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Company company0 = new Company("d:D$HS3@");
      Set<Worker> set0 = company0.getEmployedWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Company company0 = new Company("Z0X");
      String string0 = company0.getName();
      assertEquals("Z0X", string0);
  }
}
