/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 03:45:59 GMT 2026
 */

package edu.colostate.cs415.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.colostate.cs415.dto.ProjectDTO;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;
import java.util.LinkedHashSet;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Project_ESTest extends Project_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@N!Tbqo", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("Cg", linkedHashSet0, 1.0);
      project0.addWorker(worker0);
      boolean boolean0 = project0.isHelpful(worker0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Qualification qualification0 = new Qualification("6P>}k3=Q=*mELJ;");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("6P>}k3=Q=*mELJ;", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("edu.colostate.cs415.model.Project", linkedHashSet0, 6616.93);
      project0.addWorker(worker0);
      Set<Worker> set0 = project0.getWorkers();
      assertTrue(set0.contains(worker0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Qualification qualification0 = new Qualification("SUSPENDED");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("SUSPENDED", linkedHashSet0, projectSize0);
      Set<Qualification> set0 = project0.getMissingQualifications();
      assertTrue(set0.contains(qualification0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("Cannot add qualifications to an active or completed project", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.toDTO();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$3$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Qualification qualification0 = new Qualification("6P>}k3=Q=*mELJ;");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("6P>}k3=Q=*mELJ;", linkedHashSet0, projectSize0);
      project0.hashCode();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("0O@*!'TBzY");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@*!'TBzY", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.isHelpful((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      boolean boolean0 = linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@N!Tbqo", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("Cg", linkedHashSet0, 1.0);
      boolean boolean1 = project0.isHelpful(worker0);
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Qualification set cannot be null or empty");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project(", workers='", linkedHashSet0, projectSize0);
      ProjectStatus projectStatus0 = ProjectStatus.SUSPENDED;
      project0.setStatus(projectStatus0);
      // Undeclared exception!
      try { 
        project0.addQualification(qualification0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot add qualifications to an active or completed project
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("Cannot add qualifications to an active or completed project", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.addQualification((Qualification) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Qualification cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@N!Tbqo", linkedHashSet0, projectSize0);
      project0.addQualification(qualification0);
      assertEquals("0O@N!Tbqo", qualification0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("Project size cannot be null");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("Project size cannot be null", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.removeWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINIHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = new Project("FINIHED", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("FINIHED", linkedHashSet0, 625.7050211974523);
      project0.removeWorker(worker0);
      assertEquals("FINIHED", worker0.getName());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification(",PD%TA");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project(",PD%TA", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.addWorker((Worker) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@N!Tbqo", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("Cg", linkedHashSet0, 1.0);
      project0.addWorker(worker0);
      Set<Qualification> set0 = project0.getMissingQualifications();
      assertFalse(set0.contains(qualification0));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("Qualification set cannot be null or empty");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = new Project(", workers='", linkedHashSet0, projectSize0);
      // Undeclared exception!
      try { 
        project0.setStatus((ProjectStatus) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Status cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Qualification qualification0 = new Qualification("'7G");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("'7G", linkedHashSet0, projectSize0);
      Project project1 = new Project("'7G", linkedHashSet0, projectSize0);
      boolean boolean0 = project0.equals(project1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINISHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("N,?QtH'4Rr#h4?", linkedHashSet0, projectSize0);
      boolean boolean0 = project0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@N!Tbqo", linkedHashSet0, projectSize0);
      boolean boolean0 = project0.equals(project0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINISHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("N,?QtH'4Rr#h4?", linkedHashSet0, projectSize0);
      Object object0 = new Object();
      boolean boolean0 = project0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      linkedHashSet0.add(qualification0);
      Project project0 = null;
      try {
        project0 = new Project("0O@N!Tbqo", linkedHashSet0, (ProjectSize) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project size cannot be null
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Project project0 = null;
      try {
        project0 = new Project("M}&XKM", linkedHashSet0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = null;
      try {
        project0 = new Project("Cg01:1", (Set<Qualification>) null, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Project project0 = null;
      try {
        project0 = new Project("", linkedHashSet0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project name cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = null;
      try {
        project0 = new Project((String) null, linkedHashSet0, projectSize0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project name cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Project", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINISHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("N,?QtH'4Rr#h4?", linkedHashSet0, projectSize0);
      ProjectDTO projectDTO0 = project0.toDTO();
      assertEquals(ProjectSize.BIG, projectDTO0.getSize());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINISHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("N,?QtH'4Rr#h4?", linkedHashSet0, projectSize0);
      Set<Worker> set0 = project0.getWorkers();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINISHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("N,?QtH'4Rr#h4?", linkedHashSet0, projectSize0);
      Set<Qualification> set0 = project0.getRequiredQualifications();
      assertTrue(set0.contains(qualification0));
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINISHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("N,?QtH'4Rr#h4?", linkedHashSet0, projectSize0);
      ProjectStatus projectStatus0 = project0.getStatus();
      assertEquals(ProjectStatus.PLANNED, projectStatus0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("Project size cannot be null");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("Project size cannot be null", linkedHashSet0, projectSize0);
      ProjectSize projectSize1 = project0.getSize();
      assertEquals(ProjectSize.MEDIUM, projectSize1);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("FINISHED");
      linkedHashSet0.add(qualification0);
      ProjectSize projectSize0 = ProjectSize.BIG;
      Project project0 = new Project("N,?QtH'4Rr#h4?", linkedHashSet0, projectSize0);
      String string0 = project0.getName();
      assertEquals("N,?QtH'4Rr#h4?", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@N!Tbqo", linkedHashSet0, projectSize0);
      String string0 = project0.toString();
      assertEquals("0O@N!Tbqo:0:PLANNED", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Qualification qualification0 = new Qualification("0O@N!Tbqo");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("0O@N!Tbqo", linkedHashSet0, projectSize0);
      project0.removeAllWorkers();
      assertEquals(ProjectSize.BIG, project0.getSize());
  }
}
