/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 03:49:15 GMT 2026
 */

package edu.colostate.cs415.model;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.colostate.cs415.model.ProjectSize;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProjectSize_ESTest extends ProjectSize_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProjectSize[] projectSizeArray0 = ProjectSize.values();
      assertEquals(3, projectSizeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProjectSize projectSize0 = ProjectSize.valueOf("BIG");
      assertEquals(3, projectSize0.getValue());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProjectSize projectSize0 = ProjectSize.BIG;
      int int0 = projectSize0.getValue();
      assertEquals(3, int0);
  }
}
