/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 03:44:54 GMT 2026
 */

package edu.colostate.cs415.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.colostate.cs415.dto.WorkerDTO;
import edu.colostate.cs415.model.Project;
import edu.colostate.cs415.model.ProjectSize;
import edu.colostate.cs415.model.ProjectStatus;
import edu.colostate.cs415.model.Qualification;
import edu.colostate.cs415.model.Worker;

import java.util.LinkedHashSet;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Worker_ESTest extends Worker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      worker0.setSalary(0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(0.0, workerDTO0.getSalary(), 0.01);
      assertEquals(0, workerDTO0.getWorkload());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.8890426314365477);
      double double0 = worker0.getSalary();
      assertEquals(0.8890426314365477, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("{'K}(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      worker0.addProject(project0);
      worker0.getProjects();
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.toDTO();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("{'K}(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      worker0.addProject(project0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      int int0 = worker0.getWorkload();
      assertEquals(0.0, worker0.getSalary(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.MEDIUM;
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("{'K}(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      worker0.addProject(project0);
      int int0 = worker0.getWorkload();
      assertEquals(0.0, worker0.getSalary(), 0.01);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("!uK`r4`Qs8q@^NA|G");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("!uK`r4`Qs8q@^NA|G", linkedHashSet0, 0.0);
      worker0.hashCode();
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      boolean boolean0 = worker0.isAvailable();
      assertEquals(0.0, worker0.getSalary(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("q'/}y(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      boolean boolean0 = worker0.willOverload(project0);
      assertFalse(boolean0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("q'/}y(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.8890426314365477);
      boolean boolean0 = worker0.willOverload(project0);
      assertEquals(0.8890426314365477, worker0.getSalary(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.willOverload((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.SMALL;
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("q'/}y(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      worker0.addProject(project0);
      ProjectStatus projectStatus0 = ProjectStatus.FINISHED;
      project0.setStatus(projectStatus0);
      boolean boolean0 = worker0.willOverload(project0);
      assertFalse(boolean0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("q'/}y(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.8890426314365477);
      worker0.addProject(project0);
      WorkerDTO workerDTO0 = worker0.toDTO();
      assertEquals(3, workerDTO0.getWorkload());
      assertEquals(0.8890426314365477, workerDTO0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("QxW3XEF1N");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("QxW3XEF1N", linkedHashSet0, 1.96071283577024);
      // Undeclared exception!
      try { 
        worker0.removeProject((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      ProjectSize projectSize0 = ProjectSize.BIG;
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Project project0 = new Project("q'/}y(nf9ERk0", linkedHashSet0, projectSize0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.8890426314365477);
      worker0.removeProject(project0);
      assertEquals(0.8890426314365477, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      // Undeclared exception!
      try { 
        worker0.addProject((Project) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Project cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add((Qualification) null);
      Worker worker0 = new Worker("4aQPWJ]\"[`ud@%!hZwa", linkedHashSet0, 3596.853151838951);
      // Undeclared exception!
      try { 
        worker0.addQualification((Qualification) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Qualification cannot be null
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("*wQna()*");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("*wQna()*", linkedHashSet0, 0.0);
      worker0.addQualification(qualification0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("edu.colostate.cs415.model.ProjectSize");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("edu.colostate.cs415.model.ProjectSize", linkedHashSet0, 1278.1488);
      // Undeclared exception!
      try { 
        worker0.setSalary((-1.0));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Salary cannot be negative
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'}y(nf9ERk0", linkedHashSet0, 0.0);
      worker0.setSalary(12);
      assertEquals(12.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'}y(nf9ERk0", linkedHashSet0, 0.0);
      boolean boolean0 = worker0.equals(qualification0);
      assertFalse(boolean0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification(":{8V\";\"/ZJLh/_hDy");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker(":{8V\";\"/ZJLh/_hDy", linkedHashSet0, 815.2841680867841);
      boolean boolean0 = worker0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(815.2841680867841, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("{'K}(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("{'K}(nf9ERk0", linkedHashSet0, 0.0);
      boolean boolean0 = worker0.equals(worker0);
      assertTrue(boolean0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      Worker worker1 = new Worker(")KuNM^u", linkedHashSet0, 0);
      boolean boolean0 = worker0.equals(worker1);
      assertEquals(0.0, worker1.getSalary(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Qualification qualification0 = new Qualification("Worker name cannot be null or empvy");
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      linkedHashSet0.add(qualification0);
      Worker worker0 = null;
      try {
        worker0 = new Worker("Worker name cannot be null or empvy", linkedHashSet0, (-663.3));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Salary cannot be negative
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker("meJG-klEG", linkedHashSet0, 782.969374229);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Worker worker0 = null;
      try {
        worker0 = new Worker(":", (Set<Qualification>) null, (-4075.1326273817));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Qualification set cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker("", linkedHashSet0, 1823.406315425);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker name cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Worker worker0 = null;
      try {
        worker0 = new Worker((String) null, linkedHashSet0, (-3283.85660558));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Worker name cannot be null or empty
         //
         verifyException("edu.colostate.cs415.model.Worker", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      worker0.getProjects();
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      worker0.getName();
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'/}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'/}y(nf9ERk0", linkedHashSet0, 0.0);
      String string0 = worker0.toString();
      assertEquals("q'/}y(nf9ERk0:0:1:0", string0);
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'}y(nf9ERk0", linkedHashSet0, 0.0);
      worker0.getQualifications();
      assertEquals(0.0, worker0.getSalary(), 0.01);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LinkedHashSet<Qualification> linkedHashSet0 = new LinkedHashSet<Qualification>();
      Qualification qualification0 = new Qualification("q'}y(nf9ERk0");
      linkedHashSet0.add(qualification0);
      Worker worker0 = new Worker("q'}y(nf9ERk0", linkedHashSet0, 0.0);
      double double0 = worker0.getSalary();
      assertEquals(0.0, double0, 0.01);
  }
}
